server:
  port: 0
  error:
    include-message: always

#Configuracion de spring
spring:
  application:
    name: student-ms
  #Configuracion de migracion
  flyway:
    enabled: true
    baselineVersion: 1
    locations:
      classpath: db/migration
    sqlMigrationSuffixes: .sql
    baselineOnMigrate: true
    sqlMigrationPrefix: V
    schemas: public
  #Conexion a la base de datos
  datasource:
    url: jdbc:postgresql://mahmud.db.elephantsql.com:5432/xciayggm?socketTimeout=3
    username: xciayggm
    password: 9F0-bEZ1H9NHyUKVbFL-s5Klq-Vm1nEL
    driverClassName: org.postgresql.Driver

#Conexion para registro de esta API en eureka
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
